import Head from 'next/head'

import Main from './api/data.json';

import Carousel from '../components/carousel/carousel.component'

import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Слудяная фабрика</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div>
        <Carousel info = {Main.main[0].mainCarousel}/>
      </div>
    </div>
  )
}
