import Head from 'next/head'
import Image from 'next/image';

import Data from './api/data.json';

import Carousel from '../components/carousel/carousel.component'
import Products from '../components/products/products.component';

import styles from '../styles/Home.module.scss'
import Footer from '../components/footer/footer.component';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Слудяная фабрика</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Carousel info = {Data.main[0].mainCarousel} length = {6}/>
      </div>

      <h1 className = {styles.title}>Наша продукция</h1>

      <div className= {styles.products}>
        <div>
          <div className={styles.productImage}>
            <Image 
              src = '/assets/images/main/product-slyuda.png'
              height = '269px' 
              width = '201px'
              alt = 'Carousel photo'
              objectFit="contain"
              placeholder="blurDataURL"
              priority = "true"
            />
          </div>
          <h3>Слюда</h3>
          <Products info = {Data.slyuda[0].categories} styleName = 'main'/> 
        </div>

        <div>
          <div className={styles.productImage}>
            <Image 
              src = '/assets/images/main/product-vermikulit.png'
              height = '269px' 
              width = '201px'
              alt = 'Carousel photo'
              objectFit="contain"
              placeholder="blurDataURL"
              priority = "true"
            />
          </div>
          <h3>Вермикулит</h3>
          <Products info = {Data.vermikulit[0].categories} styleName = 'main'/> 
        </div>

        <div>
          <div className={styles.productImage}>
            <Image 
              src = '/assets/images/main/product-agrovermikulit.jpg'
              height = '269px' 
              width = '201px'
              alt = 'Carousel photo'
              objectFit="contain"
              placeholder="blurDataURL"
              priority = "true"
            />
          </div>
          <h3>Агровермикулит</h3>
          <Products info = {Data.agrovermikulit[0].categories} styleName = 'main'/> 
        </div>
      </div>

      <div className = {styles.description}>
        <Image
          src = '/assets/images/main/main-ad1.png'
          width = '1000'
          height = '611'
          alt = 'Carousel photo'
          objectFit="contain"
          placeholder="blurDataURL"
          priority = "true"
          style = {{borderRadius: '1em'}}
        />

        <p>
        Слюдяная фабрика живёт современной жизнью. На фабрике постоянно ведутся работы по восстановлению, реконструкции, модернизации и перепрофилированию цехов. Слюдяная фабрика стала домом не только для слюдяных производств. На территории Слюдяной фабрики трудятся предприятия строительной, атомной, металлообрабатывающей, химической и других отраслей производства. Заложенные еще в 60-е годы производственные мощности оказались сегодня особенно востребованы. Инфраструктура фабрики обеспечивает арендаторов и партнёров подъездными путями, складскими и производственными площадями, офисными помещениями.
        </p>
      </div>
      <Footer/>
    </div>
  )
}
